# Default values for kamus.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
useAirbag: false
airbag:
  repository: soluto
  tag: 0.8
image:
  version: 0.9.0.7
  repository: ghcr.io/soluto
  pullPolicy: IfNotPresent
pod:
  annotations: {}
service:
  type: ClusterIP
  name: kamus-encryptor
  port: 80
  annotations:
    prometheus.io/scrape: "true"
serviceAccount:
  annotations: {}
ingress:
  enabled: false
  ingressClassName: ''
resources:
  limits:
    cpu: 500m
    memory: 600Mi
  requests:
    cpu: 100m
    memory: 128Mi
autoscale:
  minReplicas: 2
  maxReplicas: 10
  targetCPU: 50
keyManagement:
  provider: AESKey
  AES:
    key: rWnWbaFutavdoeqUiVYMNJGvmjQh31qaIej/vAxJ9G0=
    useKeyDerivation: false
encryptor:
  automountServiceAccountToken: false
controller:
  reconciliationIntervalInSeconds: 60
