version: 2

jobs:
  lint-scripts:
    docker:
      - image: koalaman/shellcheck-alpine
    steps:
      - checkout
      - run:
          name: lint
          command: |
            shellcheck -x test/e2e-kind.sh
  lint-charts:
    docker:
      - image: quay.io/helmpack/chart-testing:v2.2.0
    steps:
      - checkout
      - run:
          command: ct lint --config test/ct.yaml
  install-charts:
    machine: true
    steps:
      - checkout
      - run:
          name: install
          command: |
            test/e2e-kind.sh
          no_output_timeout: 3600

  helm-pack:
    docker:
      - image: alpine/helm:2.12.0
    steps:
      - checkout
      - run:
          name: Helm Pack
          command: |
            mkdir packages/ 
            helm init -c 
            helm package charts/kamus/ --destination packages/
      - persist_to_workspace:
          root: packages/
          paths: 
            - "*.tgz"

  helm-deploy:
    docker:
      - image: node:8.10.0
    steps:
      - checkout
      - attach_workspace:
          at: charts/
      - run:
          name: Install and configure dependencies
          command: |
            npm install -g --silent gh-pages@2.0.1
            git config user.email "ci-build@soluto.com"
            git config user.name "ci-build"
      - add_ssh_keys:
          fingerprints:
            - "32:25:46:eb:9c:43:c0:25:4b:62:3f:f3:50:69:65:42"
      - run:
          name: Deploy docs to gh-pages branch
          command: gh-pages --add --message "[skip ci] Updates" --dist charts/

  helm-reindex:
    docker:
      - image: alpine/helm:2.12.0
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "32:25:46:eb:9c:43:c0:25:4b:62:3f:f3:50:69:65:42"
      - run:
          name: Install and configure dependencies
          command: |
            apk add --update git openssh
            git checkout gh-pages
            git config user.email "ci-build@soluto.com"
            git config user.name "ci-build"
            ssh-keyscan github.com > ~/.ssh/known_hosts
      - run:
          name: Helm Index Update
          command: |
            helm init -c
            helm repo index . --merge index.yaml
      - run:
          name: Push changes
          command: |        
            git commit -am "update repo index"
            git pull
            git push 

workflows:
  version: 2
  build:
    jobs:
      - lint-scripts:
          filters:
            branches:
              ignore: gh-pages
      - lint-charts:
          filters:
            branches:
              ignore: gh-pages
      - install-charts:
          filters:
            branches:
              ignore: gh-pages
      - helm-pack:
          filters:
            branches:
              ignore: gh-pages
      - helm-deploy:
          requires:
            - helm-pack
            - lint-scripts
            - lint-charts
            - install-charts
          filters:
            branches:
              only: master
      - helm-reindex:
          requires:
            - helm-deploy