apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "kamus.name" . }}-controller
  namespace: {{ template "kamus.namespace" . }}
data:
{{ include "common.configurations" . | indent 2 }}
  Controller__ReconciliationIntervalInSeconds: {{ .Values.controller.reconciliationIntervalInSeconds | quote }}
