{{- if .Values.ingress.enabled -}}
{{- $ingressApiIsStable := eq (include "kamus.ingress.isStable" .) "true" -}}
{{- $ingressSupportsIngressClassName := eq (include "kamus.ingress.supportsIngressClassName" .) "true" -}}
{{- $ingressSupportsPathType := eq (include "kamus.ingress.supportsPathType" .) "true" -}}
{{- $encryptorServiceName := (include "kamus.encryptor-service.name" .) -}}
apiVersion: {{ include "kamus.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ template "kamus.name" . }}
  labels:
    app: {{ template "kamus.name" . }}
    component: encryptor
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.ingress.annotations }}
  annotations:
{{ toYaml .Values.ingress.annotations | indent 4 }}
{{- end }}
spec:
  {{- if and $ingressSupportsIngressClassName .Values.ingress.ingressClassName }}
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  {{- end }}
  rules:
    {{- range $host := .Values.ingress.hosts }}
    - host: {{ $host }}
      http:
        paths:
          - path: /
            {{- if $ingressSupportsPathType }}
            pathType: Prefix
            {{- end }}
            backend:
              {{- if $ingressApiIsStable }}
              service:
                name: {{ $encryptorServiceName }}
                port:
                  name: {{ $.Values.service.port.name }}
              {{- else }}
              serviceName: {{ $encryptorServiceName }}
              servicePort: {{ $.Values.service.port.name }}
              {{- end }}
    {{- end }}
{{ if .Values.ingress.tls }}
  tls:
  - hosts:
    {{- range $host := .Values.ingress.hosts }}
      - {{ $host }}
    {{- end }}
    secretName: {{ .Values.ingress.tls.secretName }}
{{- end -}}
{{- end -}}
